In [2]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import math
import numpy as np
!pip install langdetect
from langdetect import detect
import pickle
import re

Mounted at /content/drive
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     |████████████████████████████████| 981 kB 5.3 MB/s
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from langdetect) (1.15.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993242 sha256=69e5cfec4b2653ba6287db34dcdf2bc1c8c8d7cc21a2bba728572c187e81d43b
  Stored in directory: /root/.cache/pip/wheels/c5/96/8a/f90c59ed25d75e50a8c10a1b1c2d4c402e4dacfa87f3aff36a
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [3]:
url='https://drive.google.com/file/d/10GMMASE-B3DEXh6dgCeQRUlePhdQRnFd/view?usp=sharing'
url='https://drive.google.com/uc?id=' + url.split('/')[-2]
#https://drive.google.com/file/d/10GMMASE-B3DEXh6dgCeQRUlePhdQRnFd/view?usp=sharing
#path = '/content/drive/My Drive/BT4222 yelp/yelp2017_test.csv'
yelp_t = pd.read_csv(url)

In [ ]:
!pip install contractions

Requirement already satisfied: contractions in /usr/local/lib/python3.7/dist-packages (0.1.68)
Requirement already satisfied: textsearch>=0.0.21 in /usr/local/lib/python3.7/dist-packages (from contractions) (0.0.21)
Requirement already satisfied: pyahocorasick in /usr/local/lib/python3.7/dist-packages (from textsearch>=0.0.21->contractions) (1.4.4)
Requirement already satisfied: anyascii in /usr/local/lib/python3.7/dist-packages (from textsearch>=0.0.21->contractions) (0.3.0)

In [ ]:
import contractions
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords
sb = SnowballStemmer(language = 'english')
from nltk.stem.wordnet import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
def remove_punct(token):
 return [word for word in token if word.isalpha()]

def remove_nonenglish_char(text):
  cleaned = []
  sent = word_tokenize(text)
  sent = remove_punct(sent)
  for words in sent:
    if words.isalpha():
      cleaned.append(words)
  return ' '.join(cleaned)

def expand_text(text):
  expanded_words = []
  for word in text.split():
    expanded_words.append(contractions.fix(word))
  expanded_text = ' '.join(expanded_words)
  return expanded_text

def normalize_text(text):
  stop_words = set(stopwords.words('english'))
  sent = word_tokenize(text)
  sent = remove_punct(sent)
  normalized_sent = []
  for words in sent:
    processed_word = lemmatizer.lemmatize(words)
    if processed_word.lower() not in stop_words:
      normalized_sent.append(processed_word)
  # sent = [sb.stem(words_sent) for words_sent in sent]
  # sent = [lemmatizer.lemmatize(words_sent) for words_sent in sent]
  # sent = [w for w in sent if not w.lower() in stop_words]
  return ' '.join(normalized_sent)

In [ ]:
yelp_t_12 = yelp_t.iloc[: , 1:]
yelp_t_12

,review_id,user_id,business_id,stars,date,text,useful,funny,cool,year,month,day
0,O4RZMP8IFyJTNfRp0QXEsw,u0LXt3Uea_GidxRW1xcsfg,vcxvQyAggPqxcHwvJXvjGg,4,2017-01-04,Love this place!\n\nThe cakes are delicious bu...,0.0,0.0,0.0,2017.0,1.0,4.0
1,66KqTwiQ1oB9-aTsoEN35Q,u0LXt3Uea_GidxRW1xcsfg,DKiRDPtQ5cTN-eX1oEgA9w,3,2017-01-04,It's a pub... nice and clean one.\n\nCame here...,0.0,0.0,0.0,2017.0,1.0,4.0
2,3KQ3_xutS5R3mX7HsPWpgw,u0LXt3Uea_GidxRW1xcsfg,zkU-WMio8g6dpRJ2Y2xqvQ,4,2017-01-04,Came here for dim sum - it's one of those mark...,0.0,0.0,0.0,2017.0,1.0,4.0
3,p659sFGjbL8chCRZPPyFmg,u0LXt3Uea_GidxRW1xcsfg,3RlylOY452bA8rwliPUeUQ,4,2017-01-04,My sister loves this place! Probably comes by ...,1.0,0.0,0.0,2017.0,1.0,4.0
4,1XEm85LhDeiUHdG0R_rXSQ,u0LXt3Uea_GidxRW1xcsfg,sTV4qyjDkY5cLvx2omtLyw,4,2017-02-07,Nice addition to the Distillery district! Stum...,1.0,0.0,0.0,2017.0,2.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...
902179,krfxKWE3FGJhnSuWhYHccw,4Iwu57GSychxpqa4w4HAMQ,jfmyj519pg2flxGEQ2xdPg,4,2017-06-01,We really enjoyed the food we ordered- beef wi...,0.0,0.0,0.0,2017.0,6.0,1.0
902180,dtk42P7W2JQnkogxCf3ZzQ,4Iwu57GSychxpqa4w4HAMQ,_vHI2zsJp7b02MFJUWJgbw,5,2017-06-13,The mocha cake is delicious. Yes we will drive...,0.0,0.0,0.0,2017.0,6.0,13.0
902181,8C6kBDEeVhjHPtX3dHeZzQ,n9a7RhvdydX4oesmtjTGKg,ysv6yhVYOoH9Pf7PlMyD0g,1,2017-04-02,Stopped because of the name. Food great servi...,0.0,0.0,0.0,2017.0,4.0,2.0
902182,40SDdd73-Yzom5JG4rJ44Q,jcXu20szpGPe9hDq9AR-ZA,LkMtMHVetws5_7QfRjPtlg,4,2017-05-17,I think I may have stayed at a different LVH t...,0.0,0.0,0.0,2017.0,5.0,17.0
902183,koQDtQMDv-r_D9xqFqoSxw,CPIGdVV2ByLA_nqP1F4S-Q,HeKfDaa_Fa0fn3-xy9tqDw,5,2017-05-24,I called Alaskan to schedule an appointment fo...,0.0,0.0,0.0,2017.0,5.0,24.0

In [ ]:
yelp_t_12['cleaned_text'] = yelp_t_12['text'].apply(remove_nonenglish_char)
yelp_t_12

,review_id,user_id,business_id,stars,date,text,useful,funny,cool,year,month,day,cleaned_text
0,O4RZMP8IFyJTNfRp0QXEsw,u0LXt3Uea_GidxRW1xcsfg,vcxvQyAggPqxcHwvJXvjGg,4,2017-01-04,Love this place!\n\nThe cakes are delicious bu...,0.0,0.0,0.0,2017.0,1.0,4.0,Love this place The cakes are delicious but re...
1,66KqTwiQ1oB9-aTsoEN35Q,u0LXt3Uea_GidxRW1xcsfg,DKiRDPtQ5cTN-eX1oEgA9w,3,2017-01-04,It's a pub... nice and clean one.\n\nCame here...,0.0,0.0,0.0,2017.0,1.0,4.0,It a pub nice and clean one Came here to grab ...
2,3KQ3_xutS5R3mX7HsPWpgw,u0LXt3Uea_GidxRW1xcsfg,zkU-WMio8g6dpRJ2Y2xqvQ,4,2017-01-04,Came here for dim sum - it's one of those mark...,0.0,0.0,0.0,2017.0,1.0,4.0,Came here for dim sum it one of those mark on ...
3,p659sFGjbL8chCRZPPyFmg,u0LXt3Uea_GidxRW1xcsfg,3RlylOY452bA8rwliPUeUQ,4,2017-01-04,My sister loves this place! Probably comes by ...,1.0,0.0,0.0,2017.0,1.0,4.0,My sister loves this place Probably comes by o...
4,1XEm85LhDeiUHdG0R_rXSQ,u0LXt3Uea_GidxRW1xcsfg,sTV4qyjDkY5cLvx2omtLyw,4,2017-02-07,Nice addition to the Distillery district! Stum...,1.0,0.0,0.0,2017.0,2.0,7.0,Nice addition to the Distillery district Stumb...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
902179,krfxKWE3FGJhnSuWhYHccw,4Iwu57GSychxpqa4w4HAMQ,jfmyj519pg2flxGEQ2xdPg,4,2017-06-01,We really enjoyed the food we ordered- beef wi...,0.0,0.0,0.0,2017.0,6.0,1.0,We really enjoyed the food we beef with brocco...
902180,dtk42P7W2JQnkogxCf3ZzQ,4Iwu57GSychxpqa4w4HAMQ,_vHI2zsJp7b02MFJUWJgbw,5,2017-06-13,The mocha cake is delicious. Yes we will drive...,0.0,0.0,0.0,2017.0,6.0,13.0,The mocha cake is delicious Yes we will drive ...
902181,8C6kBDEeVhjHPtX3dHeZzQ,n9a7RhvdydX4oesmtjTGKg,ysv6yhVYOoH9Pf7PlMyD0g,1,2017-04-02,Stopped because of the name. Food great servi...,0.0,0.0,0.0,2017.0,4.0,2.0,Stopped because of the name Food great service...
902182,40SDdd73-Yzom5JG4rJ44Q,jcXu20szpGPe9hDq9AR-ZA,LkMtMHVetws5_7QfRjPtlg,4,2017-05-17,I think I may have stayed at a different LVH t...,0.0,0.0,0.0,2017.0,5.0,17.0,I think I may have stayed at a different LVH t...
902183,koQDtQMDv-r_D9xqFqoSxw,CPIGdVV2ByLA_nqP1F4S-Q,HeKfDaa_Fa0fn3-xy9tqDw,5,2017-05-24,I called Alaskan to schedule an appointment fo...,0.0,0.0,0.0,2017.0,5.0,24.0,I called Alaskan to schedule an appointment fo...

In [ ]:
yelp_t_12['cleaned_text'].replace('', np.nan, inplace=True)
yelp_t_12.dropna(subset=['cleaned_text'], inplace=True)
yelp_t_12

,review_id,user_id,business_id,stars,date,text,useful,funny,cool,year,month,day,cleaned_text
0,O4RZMP8IFyJTNfRp0QXEsw,u0LXt3Uea_GidxRW1xcsfg,vcxvQyAggPqxcHwvJXvjGg,4,2017-01-04,Love this place!\n\nThe cakes are delicious bu...,0.0,0.0,0.0,2017.0,1.0,4.0,Love this place The cakes are delicious but re...
1,66KqTwiQ1oB9-aTsoEN35Q,u0LXt3Uea_GidxRW1xcsfg,DKiRDPtQ5cTN-eX1oEgA9w,3,2017-01-04,It's a pub... nice and clean one.\n\nCame here...,0.0,0.0,0.0,2017.0,1.0,4.0,It a pub nice and clean one Came here to grab ...
2,3KQ3_xutS5R3mX7HsPWpgw,u0LXt3Uea_GidxRW1xcsfg,zkU-WMio8g6dpRJ2Y2xqvQ,4,2017-01-04,Came here for dim sum - it's one of those mark...,0.0,0.0,0.0,2017.0,1.0,4.0,Came here for dim sum it one of those mark on ...
3,p659sFGjbL8chCRZPPyFmg,u0LXt3Uea_GidxRW1xcsfg,3RlylOY452bA8rwliPUeUQ,4,2017-01-04,My sister loves this place! Probably comes by ...,1.0,0.0,0.0,2017.0,1.0,4.0,My sister loves this place Probably comes by o...
4,1XEm85LhDeiUHdG0R_rXSQ,u0LXt3Uea_GidxRW1xcsfg,sTV4qyjDkY5cLvx2omtLyw,4,2017-02-07,Nice addition to the Distillery district! Stum...,1.0,0.0,0.0,2017.0,2.0,7.0,Nice addition to the Distillery district Stumb...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
902179,krfxKWE3FGJhnSuWhYHccw,4Iwu57GSychxpqa4w4HAMQ,jfmyj519pg2flxGEQ2xdPg,4,2017-06-01,We really enjoyed the food we ordered- beef wi...,0.0,0.0,0.0,2017.0,6.0,1.0,We really enjoyed the food we beef with brocco...
902180,dtk42P7W2JQnkogxCf3ZzQ,4Iwu57GSychxpqa4w4HAMQ,_vHI2zsJp7b02MFJUWJgbw,5,2017-06-13,The mocha cake is delicious. Yes we will drive...,0.0,0.0,0.0,2017.0,6.0,13.0,The mocha cake is delicious Yes we will drive ...
902181,8C6kBDEeVhjHPtX3dHeZzQ,n9a7RhvdydX4oesmtjTGKg,ysv6yhVYOoH9Pf7PlMyD0g,1,2017-04-02,Stopped because of the name. Food great servi...,0.0,0.0,0.0,2017.0,4.0,2.0,Stopped because of the name Food great service...
902182,40SDdd73-Yzom5JG4rJ44Q,jcXu20szpGPe9hDq9AR-ZA,LkMtMHVetws5_7QfRjPtlg,4,2017-05-17,I think I may have stayed at a different LVH t...,0.0,0.0,0.0,2017.0,5.0,17.0,I think I may have stayed at a different LVH t...
902183,koQDtQMDv-r_D9xqFqoSxw,CPIGdVV2ByLA_nqP1F4S-Q,HeKfDaa_Fa0fn3-xy9tqDw,5,2017-05-24,I called Alaskan to schedule an appointment fo...,0.0,0.0,0.0,2017.0,5.0,24.0,I called Alaskan to schedule an appointment fo...

In [ ]:
yelp_t_12['cleaned_text'] = yelp_t_12['cleaned_text'].apply(expand_text)
yelp_t_12['cleaned_text'] = yelp_t_12['cleaned_text'].apply(normalize_text)

In [ ]:
yelp_t_12_dropped = yelp_t_12.drop(['text'], axis=1)
yelp_t_12_dropped.to_csv('yelp_train_processed.csv',index=False)

In [ ]:
path = '/content/yelp_train_processed.csv'
yelp_r = pd.read_csv(path)

In [ ]:
yelp_r

,review_id,user_id,business_id,stars,date,useful,funny,cool,year,month,day,cleaned_text
0,O4RZMP8IFyJTNfRp0QXEsw,u0LXt3Uea_GidxRW1xcsfg,vcxvQyAggPqxcHwvJXvjGg,4,2017-01-04,0.0,0.0,0.0,2017.0,1.0,4.0,Love place cake delicious really rich cute cup...
1,66KqTwiQ1oB9-aTsoEN35Q,u0LXt3Uea_GidxRW1xcsfg,DKiRDPtQ5cTN-eX1oEgA9w,3,2017-01-04,0.0,0.0,0.0,2017.0,1.0,4.0,pub nice clean one Came grab food girl since T...
2,3KQ3_xutS5R3mX7HsPWpgw,u0LXt3Uea_GidxRW1xcsfg,zkU-WMio8g6dpRJ2Y2xqvQ,4,2017-01-04,0.0,0.0,0.0,2017.0,1.0,4.0,Came dim sum one mark sheet order dim sum pret...
3,p659sFGjbL8chCRZPPyFmg,u0LXt3Uea_GidxRW1xcsfg,3RlylOY452bA8rwliPUeUQ,4,2017-01-04,1.0,0.0,0.0,2017.0,1.0,4.0,sister love place Probably come week every two...
4,1XEm85LhDeiUHdG0R_rXSQ,u0LXt3Uea_GidxRW1xcsfg,sTV4qyjDkY5cLvx2omtLyw,4,2017-02-07,1.0,0.0,0.0,2017.0,2.0,7.0,Nice addition Distillery district Stumbled upo...
...,...,...,...,...,...,...,...,...,...,...,...,...
901998,krfxKWE3FGJhnSuWhYHccw,4Iwu57GSychxpqa4w4HAMQ,jfmyj519pg2flxGEQ2xdPg,4,2017-06-01,0.0,0.0,0.0,2017.0,6.0,1.0,really enjoyed food beef broccoli chowmein fla...
901999,dtk42P7W2JQnkogxCf3ZzQ,4Iwu57GSychxpqa4w4HAMQ,_vHI2zsJp7b02MFJUWJgbw,5,2017-06-13,0.0,0.0,0.0,2017.0,6.0,13.0,mocha cake delicious Yes drive China town need...
902000,8C6kBDEeVhjHPtX3dHeZzQ,n9a7RhvdydX4oesmtjTGKg,ysv6yhVYOoH9Pf7PlMyD0g,1,2017-04-02,0.0,0.0,0.0,2017.0,4.0,2.0,Stopped name Food great service watched waitre...
902001,40SDdd73-Yzom5JG4rJ44Q,jcXu20szpGPe9hDq9AR-ZA,LkMtMHVetws5_7QfRjPtlg,4,2017-05-17,0.0,0.0,0.0,2017.0,5.0,17.0,think may stayed different LVH reviewer going ...
902002,koQDtQMDv-r_D9xqFqoSxw,CPIGdVV2ByLA_nqP1F4S-Q,HeKfDaa_Fa0fn3-xy9tqDw,5,2017-05-24,0.0,0.0,0.0,2017.0,5.0,24.0,called Alaskan schedule appointment tune Rober...

,review_id,user_id,business_id,stars,date,useful,funny,cool,year,month,day,cleaned_text
0,O4RZMP8IFyJTNfRp0QXEsw,u0LXt3Uea_GidxRW1xcsfg,vcxvQyAggPqxcHwvJXvjGg,4,2017-01-04,0.0,0.0,0.0,2017.0,1.0,4.0,Love place cake delicious really rich cute cup...
1,66KqTwiQ1oB9-aTsoEN35Q,u0LXt3Uea_GidxRW1xcsfg,DKiRDPtQ5cTN-eX1oEgA9w,3,2017-01-04,0.0,0.0,0.0,2017.0,1.0,4.0,pub nice clean one Came grab food girl since T...
2,3KQ3_xutS5R3mX7HsPWpgw,u0LXt3Uea_GidxRW1xcsfg,zkU-WMio8g6dpRJ2Y2xqvQ,4,2017-01-04,0.0,0.0,0.0,2017.0,1.0,4.0,Came dim sum one mark sheet order dim sum pret...
3,p659sFGjbL8chCRZPPyFmg,u0LXt3Uea_GidxRW1xcsfg,3RlylOY452bA8rwliPUeUQ,4,2017-01-04,1.0,0.0,0.0,2017.0,1.0,4.0,sister love place Probably come week every two...
4,1XEm85LhDeiUHdG0R_rXSQ,u0LXt3Uea_GidxRW1xcsfg,sTV4qyjDkY5cLvx2omtLyw,4,2017-02-07,1.0,0.0,0.0,2017.0,2.0,7.0,Nice addition Distillery district Stumbled upo...
...,...,...,...,...,...,...,...,...,...,...,...,...
901998,krfxKWE3FGJhnSuWhYHccw,4Iwu57GSychxpqa4w4HAMQ,jfmyj519pg2flxGEQ2xdPg,4,2017-06-01,0.0,0.0,0.0,2017.0,6.0,1.0,really enjoyed food beef broccoli chowmein fla...
901999,dtk42P7W2JQnkogxCf3ZzQ,4Iwu57GSychxpqa4w4HAMQ,_vHI2zsJp7b02MFJUWJgbw,5,2017-06-13,0.0,0.0,0.0,2017.0,6.0,13.0,mocha cake delicious Yes drive China town need...
902000,8C6kBDEeVhjHPtX3dHeZzQ,n9a7RhvdydX4oesmtjTGKg,ysv6yhVYOoH9Pf7PlMyD0g,1,2017-04-02,0.0,0.0,0.0,2017.0,4.0,2.0,Stopped name Food great service watched waitre...
902001,40SDdd73-Yzom5JG4rJ44Q,jcXu20szpGPe9hDq9AR-ZA,LkMtMHVetws5_7QfRjPtlg,4,2017-05-17,0.0,0.0,0.0,2017.0,5.0,17.0,think may stayed different LVH reviewer going ...
902002,koQDtQMDv-r_D9xqFqoSxw,CPIGdVV2ByLA_nqP1F4S-Q,HeKfDaa_Fa0fn3-xy9tqDw,5,2017-05-24,0.0,0.0,0.0,2017.0,5.0,24.0,called Alaskan schedule appointment tune Rober...